name: ByteIR Daily CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  byteir_compiler_build_and_test:
    name: byteir compiler build and test
    runs-on: self-hosted
    container:
      image: localhost:5000/byteir-ci
      volumes:
        - /data00/llvm_libraries:/data00/llvm_libraries
        - /data00/mhlo_libraries:/data00/mhlo_libraries
        - /data00/external_libraries:/data00/external_libraries
      options: --runtime=nvidia --gpus all
    steps:
      - name: clear workspace
        run: rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout byteir repo
        uses: actions/checkout@v3
      - name: Run build and test
        run: ./scripts/compiler/build_and_test.sh
        shell: bash
  numerical_e2e_test:
    name: e2e CI
    runs-on: self-hosted
    container:
      image: localhost:5000/byteir-ci
      volumes:
        - /data00/llvm_libraries:/data00/llvm_libraries
        - /data00/mhlo_libraries:/data00/mhlo_libraries
        - /data00/external_libraries:/data00/external_libraries
      options: --runtime=nvidia --gpus all
    steps:
      - name: clear workspace
        run: rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout byteir repo
        uses: actions/checkout@v3
      - name: Build and test e2e
        run: ./scripts/e2e/build_and_test_e2e.sh
        shell: bash
