name: Format Check

on: [pull_request, workflow_dispatch]

jobs:
  clang-format-check:
    runs-on: self-hosted
    steps:
      - name: Clear workspace
        run: rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run clang-format check
        run: ./scripts/clang_format_check.sh
        shell: bash
      - name: Run other format check
        run: python3 ./scripts/format_check.py --dir $GITHUB_WORKSPACE
