name: TorchFrontend CI

on: 
  push:
    branches:
      - main
    paths:
      - "frontends/torch-frontend/**"
      - "scripts/frontends/torch-frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontends/torch-frontend/**"
      - "scripts/frontends/torch-frontend/**"
  workflow_dispatch:

# Ensure that only a single job or workflow using the same
# concurrency group will run at a time. This would cancel
# any in-progress jobs in the same github workflow and github
# ref (e.g. refs/heads/main or refs/pull/<pr_number>/merge).
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  torch_frontend_build_and_test:
    name: torch-frontend CI
    runs-on: self-hosted
    steps:
      - name: clear workspace
        run: rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout byteir repo
        uses: actions/checkout@v3
      - name: Build and test TorchFrontend
        run: ./scripts/frontends/torch-frontend/build_and_test.sh ${{ secrets.TORCH_FRONTEND_LLVM_INSTALL_DIR }}
        shell: bash
